program main
!! Generated by make_vegetable_driver. DO NOT EDIT
    implicit none

    call run()
contains
    subroutine run()
        use example_test, only: &
                example_example => test_example
        use vegetables, only: test_item_t, test_that, run_tests

        type(test_item_t) :: tests
        type(test_item_t) :: individual_tests(1)

        individual_tests(1) = example_example()
        tests = test_that(individual_tests)

        call run_tests(tests)
    end subroutine
end program
